### ISSUE TITLE
Reconcile error failing for Openstack clouds. (Openstack support missing)

### ISSUE THREAD

**Issue by usamaahmadkhan** [openshift/certman-operator#166]
I'm deploying Openshift cluster on RHOSP/vanilla openstack via Hive and facing the same issue on both of these.
After the cluster is deployed successfully, certman-operator attempts to change spec.platform which is an immutable object.

Here are the logs:
```
{"level":"info","ts":1604925442.9728994,"logger":"controller_clusterdeployment","msg":"reconciling ClusterDeployment","Request.Namespace":"cluster-stakater-binero","Request.Name":"openshift-binero"}
{"level":"info","ts":1604925442.9729996,"logger":"controller_clusterdeployment","msg":"adding CertmanOperator finalizer to the ClusterDeployment","Request.Namespace":"cluster-stakater-binero","Request.Name":"openshift-binero"}
{"level":"error","ts":1604925443.152129,"logger":"controller_clusterdeployment","msg":"error addming finalizer to ClusterDeployment","Request.Namespace":"cluster-stakater-binero","Request.Name":"openshift-binero","error":"admission webhook \"clusterdeploymentvalidators.admission.hive.openshift.io\" denied the request: Attempted to change ClusterDeployment.Spec.Platform. ClusterDeployment.Spec is immutable except for [CertificateBundles ClusterMetadata ControlPlaneConfig Ingress Installed PreserveOnDelete ClusterPoolRef PowerState HibernateAfter]","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/openshift/certman-operator/pkg/controller/clusterdeployment.(*ReconcileClusterDeployment).Reconcile\n\t/workdir/pkg/controller/clusterdeployment/clusterdeployment_controller.go:170\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1604925443.1522331,"logger":"controller_clusterdeployment","msg":"Reconcile complete.","Request.Namespace":"cluster-stakater-binero","Request.Name":"openshift-binero","Duration":0.179270139}
{"level":"error","ts":1604925443.1522815,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"clusterdeployment-controller","request":"cluster-stakater-binero/openshift-binero","error":"admission webhook \"clusterdeploymentvalidators.admission.hive.openshift.io\" denied the request: Attempted to change ClusterDeployment.Spec.Platform. ClusterDeployment.Spec is immutable except for [CertificateBundles ClusterMetadata ControlPlaneConfig Ingress Installed PreserveOnDelete ClusterPoolRef PowerState HibernateAfter]","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1604925667.8630793,"logger":"controller_clusterdeployment","msg":"reconciling ClusterDeployment","Request.Namespace":"cluster-enento-devtest","Request.Name":"cluster"}
```

My ClusterDeployment after successful installation:
```
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: openshift-binero
  namespace: cluster-stakater-binero
  finalizers:
    - hive.openshift.io/deprovision
  labels:
    api.openshift.com/managed: 'true'
    hive.openshift.io/version-major: '4'
    hive.openshift.io/version-major-minor-patch: 4.5.4
    hive.openshift.io/version-major-minor: '4.5'
    hive.openshift.io/cluster-platform: openstack
    hive.openshift.io/cluster-region: unknown
    cluster: binero
spec:
  controlPlaneConfig:
    servingCertificates:
      default: serving-cert
  clusterName: binero
  clusterMetadata:
    adminKubeconfigSecretRef:
      name: openshift-binero-0-vprlh-admin-kubeconfig
    adminPasswordSecretRef:
      name: openshift-binero-0-vprlh-admin-password
    clusterID: 4493c425-e79f-4ea0-8332-559f0c8b1385
    infraID: binero-qb5wz
  provisioning:
    imageSetRef:
      name: openshift-cluster-imageset-v4.5.4
    installConfigSecretRef:
      name: install-config
    sshPrivateKeySecretRef:
      name: ssh-key
  platform:
    openstack:
      cloud: binero
      credentialsSecretRef:
        name: cloud-creds
  ingress:
    - domain: <domain>
      name: default
      servingCertificate: serving-cert
  baseDomain: <basedomain>
  certificateBundles:
    - certificateSecretRef:
        name: serving-cert-secret-generated
      generate: true
      name: serving-cert
  installed: true
  pullSecretRef:
    name: image-pull-secret
status:
  apiURL: 'https://api.<domain>:6443'
  cliImage: >-
    quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:ddf1330bf78848849738ba17ae256ec2fb6d6ebe357f8857eefad913d4081eed
  conditions:
    - lastProbeTime: '2020-11-09T11:38:27Z'
      lastTransitionTime: '2020-11-09T11:38:27Z'
      message: >-
        secret serving-cert-secret-generated for certbundle serving-cert was not
        found
      reason: IngressCertificateNotFound
      status: 'True'
      type: IngressCertificateNotFound
    - lastProbeTime: '2020-11-09T11:40:26Z'
      lastTransitionTime: '2020-11-09T11:40:26Z'
      message: Successfully launched install pod
      reason: InstallLaunchSuccessful
      status: 'False'
      type: InstallLaunchError
    - lastProbeTime: '2020-11-09T12:17:44Z'
      lastTransitionTime: '2020-11-09T12:17:44Z'
      message: One of the SyncSet applies has failed
      reason: SyncSetApplyFailure
      status: 'True'
      type: SyncSetFailed
    - lastProbeTime: '2020-11-09T12:16:44Z'
      lastTransitionTime: '2020-11-09T12:16:44Z'
      message: >-
        One or more serving certificates for the cluster control plane are
        missing
      reason: ControlPlaneCertificatesNotFound
      status: 'True'
      type: ControlPlaneCertificateNotFound
    - lastProbeTime: '2020-11-09T12:16:45Z'
      lastTransitionTime: '2020-11-09T12:16:45Z'
      message: cluster is reachable
      reason: ClusterReachable
      status: 'False'
      type: Unreachable
  installedTimestamp: '2020-11-09T12:16:44Z'
  installerImage: >-
    quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:6d71a2c911976c33255b57277d62a8dee2972c302315a87d1f9ab64884cbbb1b
  provisionRef:
    name: openshift-binero-0-vprlh
  webConsoleURL: 'https://console-openshift-console.<domain>'

```
